# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import module.read_record_csv
import module.create_int_virt

class Ui_Form(object):

    def __init__(self):
        # print("Виклик класа")
        self.Read_PB_S_csv = []
        self.Rezult_I = []
        self.Rezult_V = []


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(316, 222)
        self.Btn_Open_PB_S = QtWidgets.QPushButton(Form)
        self.Btn_Open_PB_S.setGeometry(QtCore.QRect(10, 10, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Open_PB_S.setFont(font)
        self.Btn_Open_PB_S.setObjectName("Btn_Open_PB_S")
        self.txt_proces_label_open_PB_S = QtWidgets.QLabel(Form)
        self.txt_proces_label_open_PB_S.setGeometry(QtCore.QRect(170, 10, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_proces_label_open_PB_S.setFont(font)
        self.txt_proces_label_open_PB_S.setObjectName("txt_proces_label_open_PB_S")
        self.Btn_Gener_V_and_I = QtWidgets.QPushButton(Form)
        self.Btn_Gener_V_and_I.setGeometry(QtCore.QRect(10, 60, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Gener_V_and_I.setFont(font)
        self.Btn_Gener_V_and_I.setObjectName("Btn_Gener_V_and_I")
        self.label_progressBar = QtWidgets.QLabel(Form)
        self.label_progressBar.setGeometry(QtCore.QRect(10, 110, 290, 20))
        self.label_progressBar_2 = QtWidgets.QLabel(Form)
        self.label_progressBar_2.setGeometry(QtCore.QRect(10, 135, 290, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_progressBar.setFont(font)
        self.label_progressBar.setObjectName("label_progressBar")
        self.label_progressBar_2.setFont(font)
        self.label_progressBar_2.setObjectName("label_progressBar_2")
        # self.ProgressBar_V_and_I = QtWidgets.QProgressBar(Form)
        # self.ProgressBar_V_and_I.setGeometry(QtCore.QRect(10, 130, 290, 20))
        # self.ProgressBar_V_and_I.setProperty("value", 0)
        # self.ProgressBar_V_and_I.setObjectName("ProgressBar_V_and_I")
        self.Btn_Save_Internal = QtWidgets.QPushButton(Form)
        self.Btn_Save_Internal.setGeometry(QtCore.QRect(10, 180, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Save_Internal.setFont(font)
        self.Btn_Save_Internal.setObjectName("Btn_Save_Internal")
        self.Btn_Save_Virtual = QtWidgets.QPushButton(Form)
        self.Btn_Save_Virtual.setGeometry(QtCore.QRect(170, 180, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Save_Virtual.setFont(font)
        self.Btn_Save_Virtual.setObjectName("Btn_Save_Virtual")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Leps.V1"))
        self.Btn_Open_PB_S.setText(_translate("Form", "Open PB_S"))
        self.Btn_Open_PB_S.clicked.connect(self.clicer_Btn_Open_PB_S)
        self.txt_proces_label_open_PB_S.setText(_translate("Form", "PB_S is NOT loaded"))
        self.Btn_Gener_V_and_I.setText(_translate("Form", "Generate Virtual and Internal"))
        self.Btn_Gener_V_and_I.clicked.connect(self.clicer_Btn_Gener_V_and_I)
        self.label_progressBar.setText(_translate("Form", "Virtual and internal generation status:"))
        self.label_progressBar_2.setText(_translate("Form", "NOT yet generated"))
        self.Btn_Save_Internal.setText(_translate("Form", "Save_Internal"))
        self.Btn_Save_Internal.clicked.connect(self.clicer_Btn_Save_Internal)
        self.Btn_Save_Virtual.setText(_translate("Form", "Save_Virtual"))
        self.Btn_Save_Virtual.clicked.connect(self.clicer_Btn_Save_Virtual)

    def clicer_Btn_Open_PB_S(self):
        openFilePB_S = QFileDialog.getOpenFileName()
        if openFilePB_S:
            name_open_file = openFilePB_S[0].split("/")
            # print(name_open_file)
            self.txt_proces_label_open_PB_S.setText(name_open_file[len(name_open_file) - 1])

            self.Read_PB_S_csv = module.read_record_csv.read(openFilePB_S[0])
            # print(self.Read_PB_S_csv)

    def clicer_Btn_Gener_V_and_I(self):
        # print(self.Read_PB_S_csv)
        self.Rezult_I = module.create_int_virt.create_I(self.Read_PB_S_csv)
        self.Rezult_V = module.create_int_virt.create_V(self.Read_PB_S_csv)
        _translate = QtCore.QCoreApplication.translate
        self.label_progressBar_2.setText(_translate("Form", "GENERATED"))


    def clicer_Btn_Save_Internal(self):
        way_for_w_I = QFileDialog.getSaveFileName(filter='Data File (*.csv)')
        if way_for_w_I:
            module.read_record_csv.record(self.Rezult_I, way_for_w_I[0])


    def clicer_Btn_Save_Virtual(self):
        way_for_w_V = QFileDialog.getSaveFileName(filter='Data File (*.csv)')
        if way_for_w_V:
            module.read_record_csv.record(self.Rezult_V, way_for_w_V[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
